name: Conventional commits check
on:
  pull_request:
    branches: [trunk]

jobs:
  cog_check:
    name: Check conventional commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Conventional commits check
        uses: cocogitto/cocogitto-action@c7a74f5406bab86da17da0f0e460a69f8219a68c # v3.11.0
        with:
          check-latest-tag-only: false
